export default marks = [
  {
    userId: 'ymkVsyXGDnfN5SjeWhfOmUCHgQ72',
    name: 'Design and Analysis of Algorithm',
    semester: 1,
    type: 'Assignment',
    totalMarks: 200,
    obtainedMarks: 199,
    weightage: 10,
  },
  {
    userId: 'ymkVsyXGDnfN5SjeWhfOmUCHgQ72',
    name: 'Design and Analysis of Algorithm',
    semester: 1,
    type: 'Mid 1',
    totalMarks: 200,
    obtainedMarks: 199,
    weightage: 10,
  },
  {
    userId: 'ymkVsyXGDnfN5SjeWhfOmUCHgQ72',
    name: 'Design and Analysis of Algorithm',
    semester: 1,
    type: 'Mid 2',
    totalMarks: 200,
    obtainedMarks: 199,
    weightage: 10,
  },
  {
    userId: 'ymkVsyXGDnfN5SjeWhfOmUCHgQ72',
    name: 'Design and Analysis of Algorithm',
    semester: 1,
    type: 'Final',
    totalMarks: 200,
    obtainedMarks: 199,
    weightage: 10,
  },
];
